//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationAdminREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public campu()
        {
            this.classrooms = new HashSet<classroom>();
        }
    
        public int id { get; set; }
        public int address_id { get; set; }
        public int faculty_id { get; set; }
        public string name { get; set; }
    
        public virtual address address { get; set; }
        public virtual faculty faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<classroom> classrooms { get; set; }
    }
}
