//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationAdminREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lecture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lecture()
        {
            this.attendance_record = new HashSet<attendance_record>();
            this.classes = new HashSet<@class>();
            this.teachers = new HashSet<teacher>();
        }
    
        public int id { get; set; }
        public int course_id { get; set; }
        public int classroom_id { get; set; }
        public string name { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time_start { get; set; }
        public System.TimeSpan time_end { get; set; }
        public int time_zone { get; set; }
        public int length { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> registration_deadline { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attendance_record> attendance_record { get; set; }
        public virtual classroom classroom { get; set; }
        public virtual course course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<@class> classes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teacher> teachers { get; set; }
    }
}
