//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace EducationAdminREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.attendance_record = new HashSet<attendance_record>();
            this.users = new HashSet<user>();
        }
    
        public int id { get; set; }
        public int class_id { get; set; }
        public Nullable<int> network_id { get; set; }
        public Nullable<int> gps_coordinates_id { get; set; }
        public string forename { get; set; }
        public string surname { get; set; }
        public string email_address { get; set; }
        public string phone_number { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attendance_record> attendance_record { get; set; }
        public virtual gps_coordinates gps_coordinates { get; set; }
        public virtual network network { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
        public virtual iclass iclass { get; set; }
    }
}
