//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace EducationAdminREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.authorities = new HashSet<authority>();
        }
    
        public string username { get; set; }
        public string password { get; set; }
        public bool enabled { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> teacher_id { get; set; }
    
        public virtual student student { get; set; }
        public virtual teacher teacher { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<authority> authorities { get; set; }
    }
}
